AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # Amazon Athenaで実行したクエリ結果を保管する先
  AthenaQueryBucket:
    Properties:
      BucketName: 'athena-query-bucket-sample'
    Type: 'AWS::S3::Bucket'

  # Kinesis Data Firehoseの配信ストリーム送信先
  KinesisDataBucket:
    Properties:
      BucketName: 'kinesis-data-bucket-sample'
    Type: 'AWS::S3::Bucket'

  LogsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'logs.ap-northeast-1.amazonaws.com'
            Action: 'sts:AssumeRole'
